# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'News' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News

 # Network Layer
  pod 'Alamofire', '~> 4.8.2'

  # R.swift
  pod 'R.swift', '~> 5.1'
  
  #images
  pod 'Kingfisher', '~> 5.13'
  
  #RealmDB
  pod 'RealmSwift'

  target 'NewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsUITests' do
    # Pods for testing
  end

end
